/** Core domain types for ClearTrial. */

/** A single eligibility line as published by ClinicalTrials.gov. */
export type RawCriterion = string;

export interface Trial {
  nctId: string;
  title: string;
  officialTitle: string | null;
  status: string | null;
  phase: string;
  conditions: string[];
  interventions: string[];
  inclusion: RawCriterion[];
  exclusion: RawCriterion[];
  url: string;
}

export interface TrialsFile {
  source: string;
  sponsor: string;
  fetchedAt: string;
  count: number;
  trials: Trial[];
}

/**
 * Structured patient facts. Every field is nullable: the extractor is
 * instructed never to infer a value the patient did not state, and the
 * matcher treats null as "unknown", never as "passes".
 */
export interface PatientProfile {
  cancerType: string | null;
  /** Free-text stage as stated, e.g. "Stage IV". */
  stage: string | null;
  /** Normalized 1-4 when a roman/arabic stage is stated. */
  stageNumber: number | null;
  priorTherapies: string[];
  /** Drug/class tokens normalized for matching, e.g. "platinum", "pd-1". */
  priorTherapyClasses: string[];
  biomarkers: string[];
  /** PD-L1 tumor proportion score as a percentage, when stated. */
  pdl1Percent: number | null;
  ecog: number | null;
  hasBrainMets: boolean | null;
  ageYears: number | null;
  /** Verbatim phrases the patient used, for the "we read this" UI. */
  quotes: string[];
}

/** The categories of criterion the deterministic engine can evaluate. */
export type RuleKind =
  | "condition"
  | "ecog"
  | "prior_platinum"
  | "prior_checkpoint_inhibitor"
  | "prior_lines"
  | "pdl1_threshold"
  | "brain_mets"
  | "measurable_disease"
  | "stage"
  | "age"
  | "unparsed";

export type CriterionOutcome = "pass" | "fail" | "unknown";

export interface EvaluatedCriterion {
  kind: RuleKind;
  /** The published trial text this was derived from. */
  source: RawCriterion;
  outcome: CriterionOutcome;
  /** Human-readable justification, generated by code, not the LLM. */
  detail: string;
  /** Which side of the protocol this came from. */
  side: "inclusion" | "exclusion";
}

export type MatchVerdict = "eligible" | "likely" | "excluded" | "needs_review";

export interface MatchResult {
  trial: Trial;
  verdict: MatchVerdict;
  /** 0-100, derived only from evaluated criteria. Not model output. */
  score: number;
  evaluated: EvaluatedCriterion[];
  /** Criteria that ruled the patient out. Drives the dashboard signal. */
  blockers: EvaluatedCriterion[];
  /** Criteria the engine could not decide without more information. */
  openQuestions: EvaluatedCriterion[];
}

/**
 * An anonymized record of why an interested patient failed to match.
 * This is the raw material for the Researcher Dashboard.
 */
export interface UnmatchedSignal {
  kind: RuleKind;
  /** Short label for the dashboard, e.g. "ECOG 0-1 required". */
  label: string;
  /** How many trials in this search rejected the patient for this reason. */
  trialsBlocked: number;
  exampleTrial: string;
  exampleCriterion: string;
}

export interface MatchResponse {
  profile: PatientProfile;
  results: MatchResult[];
  signals: UnmatchedSignal[];
  /** True when the OpenAI call was skipped or failed and mock data was used. */
  usedFallback: boolean;
  model: string | null;
  elapsedMs: number;
}
