"use client";

import { useState } from "react";
import { Check, ChevronDown, CircleHelp, Mail, X } from "lucide-react";
import type { MatchResult, MatchVerdict } from "@/lib/types";

const VERDICT: Record<MatchVerdict, { label: string; cls: string }> = {
  eligible: {
    label: "Looks like a match",
    cls: "border-[color:var(--ct-teal-border)] bg-[var(--ct-teal-bg)] text-[var(--ct-teal-text)]",
  },
  likely: {
    label: "Possible match",
    cls: "border-[color:var(--ct-sky-border)] bg-[var(--ct-sky-bg)] text-[var(--ct-sky-text)]",
  },
  needs_review: {
    label: "Needs your doctor to confirm",
    cls: "border-[color:var(--ct-slate-chip-border)] bg-[var(--ct-slate-chip-bg)] text-[var(--ct-slate-chip-text)]",
  },
  excluded: {
    label: "Not a fit right now",
    cls: "border-[color:var(--ct-rose-border)] bg-[var(--ct-rose-bg)] text-[var(--ct-rose-text)]",
  },
};

function draftEmail(r: MatchResult) {
  const subject = `Question about trial ${r.trial.nctId}`;
  const reasons = r.evaluated
    .filter((c) => c.outcome === "pass")
    .slice(0, 3)
    .map((c) => `- ${c.detail}`)
    .join("\n");
  const questions = r.openQuestions
    .slice(0, 3)
    .map((c) => `- ${c.detail}`)
    .join("\n");

  const body = [
    `Hello,`,
    ``,
    `I found this study while looking for options and I think I may be eligible:`,
    `${r.trial.title}`,
    `${r.trial.url}`,
    ``,
    reasons ? `Based on my history:\n${reasons}` : ``,
    ``,
    questions ? `I still need to confirm:\n${questions}` : ``,
    ``,
    `Could someone let me know what the next step would be?`,
    ``,
    `Thank you.`,
  ]
    .filter(Boolean)
    .join("\n");

  return `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

export function TrialCard({ result }: { result: MatchResult }) {
  const [open, setOpen] = useState(false);
  const v = VERDICT[result.verdict];
  const passes = result.evaluated.filter((c) => c.outcome === "pass");

  return (
    <div className="ct-card rounded-xl p-5">
      <div className="flex items-start justify-between gap-4">
        <div className="min-w-0">
          <div className="mb-2 flex flex-wrap items-center gap-2">
            <span className={`rounded-md border px-2 py-0.5 text-[11px] ${v.cls}`}>
              {v.label}
            </span>
            <span className="rounded-md border border-[color:var(--ct-border-strong)] px-2 py-0.5 text-[11px] text-[var(--ct-text-muted)]">
              {result.trial.phase.replace(/PHASE/g, "Phase ")}
            </span>
            <a
              href={result.trial.url}
              target="_blank"
              rel="noreferrer"
              className="font-mono text-[11px] text-[var(--ct-text-soft)] transition-colors hover:text-[var(--ct-text)]"
            >
              {result.trial.nctId} ↗
            </a>
          </div>
          <h3 className="text-sm font-medium leading-snug text-[var(--ct-text)]">
            {result.trial.title}
          </h3>
          {result.trial.interventions.length > 0 && (
            <p className="mt-1 text-xs text-[var(--ct-text-soft)]">
              {result.trial.interventions.slice(0, 4).join(" · ")}
            </p>
          )}
        </div>
        {/*
          Two numbers, not one. A single "confidence" score hid the fact that a
          trial could show 100 after checking a single requirement. Fit says how
          much of what we checked the patient met; coverage says how much we
          were able to check at all.
        */}
        <div className="shrink-0 text-right">
          <div className="text-2xl font-semibold tabular-nums text-[var(--ct-text)]">
            {result.fit}
            <span className="text-sm font-normal text-[var(--ct-text-soft)]">%</span>
          </div>
          <div className="text-[10px] uppercase tracking-wide text-[var(--ct-text-soft)]">
            fit
          </div>
          <div className="mt-1 text-[10px] tabular-nums text-[var(--ct-text-soft)]">
            checked {result.coverage.checked} of {result.coverage.total}
          </div>
        </div>
      </div>

      {/* Why this matched — generated by the matching engine, not the model. */}
      {passes.length > 0 && (
        <ul className="mt-4 space-y-1.5">
          {passes.slice(0, 3).map((c, i) => (
            <li key={i} className="flex gap-2 text-xs text-[var(--ct-text-muted)]">
              <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--ct-accent)]" />
              <span>{c.detail}</span>
            </li>
          ))}
        </ul>
      )}

      {result.blockers.length > 0 && (
        <ul className="mt-3 space-y-1.5">
          {result.blockers.slice(0, 2).map((c, i) => (
            <li key={i} className="flex gap-2 text-xs text-[var(--ct-rose-text)]">
              <X className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--ct-rose-text)]" />
              <span>{c.detail}</span>
            </li>
          ))}
        </ul>
      )}

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <a
          href={draftEmail(result)}
          className="inline-flex items-center gap-1.5 rounded-lg bg-[var(--ct-accent)] px-3 py-1.5 text-xs font-medium text-[var(--ct-accent-ink)] transition-colors hover:bg-[var(--ct-accent-hover)]"
        >
          <Mail className="h-3.5 w-3.5" />
          Draft email to the study team
        </a>
        <button
          onClick={() => setOpen((o) => !o)}
          className="inline-flex items-center gap-1 text-xs text-[var(--ct-text-muted)] transition-colors hover:text-[var(--ct-text)]"
        >
          <ChevronDown
            className={`h-3.5 w-3.5 transition-transform ${open ? "rotate-180" : ""}`}
          />
          {open ? "Hide" : "What would taking part involve?"}
        </button>
      </div>

      {open && (
        <div className="mt-4 space-y-3 border-t border-[color:var(--ct-border)] pt-4">
          {result.openQuestions.length > 0 && (
            <div>
              <p className="mb-1.5 text-[11px] uppercase tracking-wide text-[var(--ct-text-soft)]">
                Your doctor will need to confirm
              </p>
              <ul className="space-y-1">
                {result.openQuestions.slice(0, 4).map((c, i) => (
                  <li key={i} className="flex gap-2 text-xs text-[var(--ct-text-muted)]">
                    <CircleHelp className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--ct-text-soft)]" />
                    <span>{c.detail}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          {/*
            The requirements no rule could read. These used to be computed and
            then silently dropped, which is how a card could look fully checked
            when most of the protocol had never been examined.
          */}
          {result.unreadable.length > 0 && (
            <div>
              <p className="mb-1.5 text-[11px] uppercase tracking-wide text-[var(--ct-text-soft)]">
                {result.unreadable.length} other requirement
                {result.unreadable.length === 1 ? "" : "s"} your doctor will
                need to read
              </p>
              <ul className="space-y-1">
                {result.unreadable.slice(0, 2).map((c, i) => (
                  <li key={i} className="text-xs italic text-[var(--ct-text-soft)]">
                    “{c.source.length > 150 ? `${c.source.slice(0, 150)}…` : c.source}”
                  </li>
                ))}
              </ul>
            </div>
          )}
          <div>
            <p className="mb-1.5 text-[11px] uppercase tracking-wide text-[var(--ct-text-soft)]">
              Conditions studied
            </p>
            <p className="text-xs text-[var(--ct-text-muted)]">
              {result.trial.conditions.join(" · ")}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
